apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: test-rs-app-multiport
  labels:
    type: app12
spec:
  replicas: 2
  selector:
    matchLabels:
      type: app12
  template:
    metadata:
      labels:
        type: app12
    spec:
      containers:
      - name: test-app-multiport
        image: etlars/multi-server:v3
        ports:
        - containerPort: 8081
        - containerPort: 8082
