apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: test-rs-app
  labels:
    type: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      type: app1
  template:
    metadata:
      labels:
        type: app1
    spec:
      containers:
      - name: test-container-app
        image: etlars/node_app:v1
        ports:
        - containerPort: 8080
